
from chfsm import CHFSM
from time import sleep

# varsious Pi and circuit-specific constants
RGB_ACTIVE_HIGH = False
CH_RELAY_ACTIVE_HIGH = False
HW_RELAY_ACTIVE_HIGH = False

RED_LED_PIN = 12
GREN_LED_PIN = 19
BLUE_LED_PIN = 13

HW_RELAY_PIN = 14
CH_RELAY_PIN = 15

HW_SWITCH_PIN = 16
CH_SWITCH_PIN = 20


fsm = CHFSM(RED_LED_PIN, GREN_LED_PIN, BLUE_LED_PIN, HW_RELAY_PIN, CH_RELAY_PIN, HW_SWITCH_PIN, CH_SWITCH_PIN, RGB_ACTIVE_HIGH, CH_RELAY_ACTIVE_HIGH, HW_RELAY_ACTIVE_HIGH)

while 1:
    fsm.process()
    sleep(2)




